# Generated by Django 4.0.5 on 2022-06-29 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sneakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SizesSneakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_34', models.IntegerField(default=0)),
                ('size_35', models.IntegerField(default=0)),
                ('size_36', models.IntegerField(default=0)),
                ('size_37', models.IntegerField(default=0)),
                ('size_38', models.IntegerField(default=0)),
                ('size_39', models.IntegerField(default=0)),
                ('size_40', models.IntegerField(default=0)),
                ('size_41', models.IntegerField(default=0)),
                ('size_42', models.IntegerField(default=0)),
                ('size_43', models.IntegerField(default=0)),
                ('size_44', models.IntegerField(default=0)),
                ('size_45', models.IntegerField(default=0)),
                ('size_46', models.IntegerField(default=0)),
                ('sneaker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.sneakers')),
            ],
        ),
    ]
