# Generated by Django 4.0.5 on 2022-06-28 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizesSneakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_34', models.IntegerField()),
                ('size_35', models.IntegerField()),
                ('size_36', models.IntegerField()),
                ('size_37', models.IntegerField()),
                ('size_38', models.IntegerField()),
                ('size_39', models.IntegerField()),
                ('size_40', models.IntegerField()),
                ('size_41', models.IntegerField()),
                ('size_42', models.IntegerField()),
                ('size_43', models.IntegerField()),
                ('size_44', models.IntegerField()),
                ('size_45', models.IntegerField()),
                ('size_46', models.IntegerField()),
                ('sneaker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.sneakers')),
            ],
        ),
    ]
