# Generated by Django 4.0.6 on 2022-07-09 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sizessneaker',
            name='sneaker_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='store.sneaker'),
        ),
    ]
