# Generated by Django 4.0.5 on 2022-06-29 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_sizessneakers_sneaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='size_config',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.sizessneakers'),
            preserve_default=False,
        ),
    ]
