# Generated by Django 4.0.5 on 2022-06-29 09:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_sizessneakers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizessneakers',
            name='size_34',
        ),
        migrations.RemoveField(
            model_name='sizessneakers',
            name='size_35',
        ),
        migrations.RemoveField(
            model_name='sizessneakers',
            name='size_36',
        ),
        migrations.RemoveField(
            model_name='sizessneakers',
            name='size_37',
        ),
        migrations.RemoveField(
            model_name='sizessneakers',
            name='size_38',
        ),
        migrations.RemoveField(
            model_name='sizessneakers',
            name='size_39',
        ),
        migrations.RemoveField(
            model_name='sizessneakers',
            name='size_40',
        ),
        migrations.RemoveField(
            model_name='sizessneakers',
            name='size_41',
        ),
        migrations.RemoveField(
            model_name='sizessneakers',
            name='size_42',
        ),
        migrations.RemoveField(
            model_name='sizessneakers',
            name='size_43',
        ),
        migrations.RemoveField(
            model_name='sizessneakers',
            name='size_44',
        ),
        migrations.RemoveField(
            model_name='sizessneakers',
            name='size_45',
        ),
        migrations.RemoveField(
            model_name='sizessneakers',
            name='size_46',
        ),
        migrations.AddField(
            model_name='sizessneakers',
            name='sizes',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(34), django.core.validators.MaxValueValidator(45)]),
            preserve_default=False,
        ),
    ]
