# Generated by Django 4.0.6 on 2022-07-09 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_sizessneaker_sneaker_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizessneaker',
            name='size_34',
        ),
        migrations.AddField(
            model_name='sizessneaker',
            name='size_35_5',
            field=models.PositiveIntegerField(default=0, verbose_name='35.5'),
        ),
        migrations.AddField(
            model_name='sizessneaker',
            name='size_36_5',
            field=models.PositiveIntegerField(default=0, verbose_name='36.5'),
        ),
        migrations.AddField(
            model_name='sizessneaker',
            name='size_37_5',
            field=models.PositiveIntegerField(default=0, verbose_name='37.5'),
        ),
        migrations.AddField(
            model_name='sizessneaker',
            name='size_38_5',
            field=models.PositiveIntegerField(default=0, verbose_name='38.5'),
        ),
        migrations.AddField(
            model_name='sizessneaker',
            name='size_40_5',
            field=models.PositiveIntegerField(default=0, verbose_name='40.5'),
        ),
        migrations.AddField(
            model_name='sizessneaker',
            name='size_42_5',
            field=models.PositiveIntegerField(default=0, verbose_name='42.5'),
        ),
        migrations.AddField(
            model_name='sizessneaker',
            name='size_44_5',
            field=models.PositiveIntegerField(default=0, verbose_name='44.5'),
        ),
        migrations.AddField(
            model_name='sizessneaker',
            name='size_46',
            field=models.PositiveIntegerField(default=0, verbose_name='46'),
        ),
        migrations.AddField(
            model_name='sizessneaker',
            name='size_46_5',
            field=models.PositiveIntegerField(default=0, verbose_name='45.5'),
        ),
        migrations.AlterField(
            model_name='sizessneaker',
            name='size_35',
            field=models.PositiveIntegerField(default=0, verbose_name='35'),
        ),
        migrations.AlterField(
            model_name='sizessneaker',
            name='size_36',
            field=models.PositiveIntegerField(default=0, verbose_name='36'),
        ),
        migrations.AlterField(
            model_name='sizessneaker',
            name='size_37',
            field=models.PositiveIntegerField(default=0, verbose_name='37'),
        ),
        migrations.AlterField(
            model_name='sizessneaker',
            name='size_38',
            field=models.PositiveIntegerField(default=0, verbose_name='38'),
        ),
        migrations.AlterField(
            model_name='sizessneaker',
            name='size_39',
            field=models.PositiveIntegerField(default=0, verbose_name='39'),
        ),
        migrations.AlterField(
            model_name='sizessneaker',
            name='size_40',
            field=models.PositiveIntegerField(default=0, verbose_name='40'),
        ),
        migrations.AlterField(
            model_name='sizessneaker',
            name='size_41',
            field=models.PositiveIntegerField(default=0, verbose_name='41'),
        ),
        migrations.AlterField(
            model_name='sizessneaker',
            name='size_42',
            field=models.PositiveIntegerField(default=0, verbose_name='42'),
        ),
        migrations.AlterField(
            model_name='sizessneaker',
            name='size_43',
            field=models.PositiveIntegerField(default=0, verbose_name='43'),
        ),
        migrations.AlterField(
            model_name='sizessneaker',
            name='size_44',
            field=models.PositiveIntegerField(default=0, verbose_name='44'),
        ),
        migrations.AlterField(
            model_name='sizessneaker',
            name='size_45',
            field=models.PositiveIntegerField(default=0, verbose_name='45'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='Брэнд'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='gender',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('U', 'Unisex')], max_length=2, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='image1',
            field=models.ImageField(upload_to='images', verbose_name='Фото 1'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='image2',
            field=models.ImageField(upload_to='images', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='image3',
            field=models.ImageField(upload_to='images', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='image4',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Фото 4'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='image5',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Фото 5'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='image6',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Фото 6'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='price',
            field=models.FloatField(verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Наименование'),
        ),
    ]
