# Generated by Django 4.0.5 on 2022-06-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_sizessneakers_size_34_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizessneakers',
            name='sizes',
        ),
        migrations.AddField(
            model_name='sizessneakers',
            name='size_34',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sizessneakers',
            name='size_35',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sizessneakers',
            name='size_36',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sizessneakers',
            name='size_37',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sizessneakers',
            name='size_38',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sizessneakers',
            name='size_39',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sizessneakers',
            name='size_40',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sizessneakers',
            name='size_41',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sizessneakers',
            name='size_42',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sizessneakers',
            name='size_43',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sizessneakers',
            name='size_44',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sizessneakers',
            name='size_45',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sizessneakers',
            name='size_46',
            field=models.IntegerField(default=0),
        ),
    ]
