# Generated by Django 4.0.6 on 2022-07-09 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_sizessneaker_size_34_sizessneaker_size_35_5_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Список товаров', 'verbose_name_plural': 'Список товаров'},
        ),
        migrations.AlterModelOptions(
            name='orderlist',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='sizessneaker',
            options={'verbose_name': 'Размеры', 'verbose_name_plural': 'Размеры'},
        ),
        migrations.AlterModelOptions(
            name='sneaker',
            options={'verbose_name': 'Кроссовки', 'verbose_name_plural': 'Кроссовки'},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sneaker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.sneaker', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='sneaker_size',
            field=models.IntegerField(verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='customer',
            field=models.CharField(max_length=128, verbose_name='ФИО клиента'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='Доставлено'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='given_to_work',
            field=models.BooleanField(default=False, verbose_name='Отдано в работу'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='shipping_address',
            field=models.CharField(max_length=128, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='image4',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Фото 4 (необязательно)'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='image5',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Фото 5 (необязательно)'),
        ),
        migrations.AlterField(
            model_name='sneaker',
            name='image6',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='Фото 6 (необязательно)'),
        ),
    ]
