# Generated by Django 4.0.5 on 2022-06-29 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_sneakers_size_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneakers',
            name='size_config',
        ),
        migrations.AddField(
            model_name='sizessneakers',
            name='sneaker',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.sneakers'),
            preserve_default=False,
        ),
    ]
