# Generated by Django 4.0.5 on 2022-06-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_sneakers_size_config_sizessneakers_sneaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='des',
            field=models.TextField(default=222),
            preserve_default=False,
        ),
    ]
