# Generated by Django 4.0.5 on 2022-07-04 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_sneakers_des'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneakers',
            name='des',
        ),
    ]
