# Generated by Django 4.0.5 on 2022-07-04 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_sneakers_des'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='sneaker_sizes',
            field=models.JSONField(default=2),
            preserve_default=False,
        ),
    ]
