# Generated by Django 4.0.5 on 2022-07-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_sneakers_sneaker_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sneakers',
            name='sneaker_sizes',
            field=models.JSONField(default={'34': 0, '35': 0, '36': 0, '37': 0, '38': 0, '39': 0, '40': 0, '41': 0, '42': 0, '43': 0, '44': 0, '45': 0}),
        ),
    ]
