# Generated by Django 4.0.5 on 2022-07-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_sneakers_sneaker_sizes'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='gender',
            field=models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('U', 'Unisex')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
