# Generated by Django 4.0.6 on 2022-07-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_vegetables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='order_id',
        ),
    ]
