# Generated by Django 4.0.6 on 2022-07-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_vegetables', '0002_remove_orderlist_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='comment',
            field=models.CharField(blank=True, max_length=2000, verbose_name='Комментарий'),
        ),
    ]
